INSERT INTO coupling_scan_candidates (
    task_run_id,
    candidate_order,
    service_date,
    bureau,
    model,
    candidate_emu_id,
    status,
    reason,
    scanned_train_prefix,
    scanned_train_number,
    scanned_internal_code,
    scanned_start_at,
    matched_train_prefix,
    matched_train_number,
    matched_start_at,
    train_repeat,
    detail_json,
    created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
