// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    GetAdminTrainProvenanceCouplingScanRequestSchema,
    GetAdminTrainProvenanceCouplingScanResponseSchema,
    GetAdminTrainProvenanceCouplingScanTasksRequestSchema,
    GetAdminTrainProvenanceCouplingScanTasksResponseSchema,
    GetAdminTrainProvenanceQrcodeScanRequestSchema,
    GetAdminTrainProvenanceQrcodeScanResponseSchema,
    GetAdminTrainProvenanceQrcodeScanTasksRequestSchema,
    GetAdminTrainProvenanceQrcodeScanTasksResponseSchema,
    GetAdminTrainProvenanceRequestSchema,
    GetAdminTrainProvenanceRequestStatsRequestSchema,
    GetAdminTrainProvenanceRequestStatsResponseSchema,
    GetAdminTrainProvenanceResponseSchema,
    GetAdminTrainProvenanceStationBoardRequestSchema,
    GetAdminTrainProvenanceStationBoardResponseSchema,
    GetAdminTrainProvenanceStationBoardTasksRequestSchema,
    GetAdminTrainProvenanceStationBoardTasksResponseSchema,
    GetAdminTrainProvenanceStationPlatformRefreshRequestSchema,
    GetAdminTrainProvenanceStationPlatformRefreshResponseSchema
} from '#shared/generated/proto/opencrh/v2/admin_provenance_pb';
import type { V2ClientOperation } from './types';

export const ADMINPROVENANCE_V2_OPERATIONS = {
    GetAdminTrainProvenance: {
        operationName: 'GetAdminTrainProvenance',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance',
        requestSchema: GetAdminTrainProvenanceRequestSchema,
        responseSchema: GetAdminTrainProvenanceResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceCouplingScan: {
        operationName: 'GetAdminTrainProvenanceCouplingScan',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/coupling-scan',
        requestSchema: GetAdminTrainProvenanceCouplingScanRequestSchema,
        responseSchema: GetAdminTrainProvenanceCouplingScanResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceCouplingScanTasks: {
        operationName: 'GetAdminTrainProvenanceCouplingScanTasks',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/coupling-scan-tasks',
        requestSchema: GetAdminTrainProvenanceCouplingScanTasksRequestSchema,
        responseSchema: GetAdminTrainProvenanceCouplingScanTasksResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceQrcodeScan: {
        operationName: 'GetAdminTrainProvenanceQrcodeScan',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/qrcode-scan',
        requestSchema: GetAdminTrainProvenanceQrcodeScanRequestSchema,
        responseSchema: GetAdminTrainProvenanceQrcodeScanResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceQrcodeScanTasks: {
        operationName: 'GetAdminTrainProvenanceQrcodeScanTasks',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/qrcode-scan-tasks',
        requestSchema: GetAdminTrainProvenanceQrcodeScanTasksRequestSchema,
        responseSchema: GetAdminTrainProvenanceQrcodeScanTasksResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceRequestStats: {
        operationName: 'GetAdminTrainProvenanceRequestStats',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/request-stats',
        requestSchema: GetAdminTrainProvenanceRequestStatsRequestSchema,
        responseSchema: GetAdminTrainProvenanceRequestStatsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceStationBoard: {
        operationName: 'GetAdminTrainProvenanceStationBoard',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/station-board',
        requestSchema: GetAdminTrainProvenanceStationBoardRequestSchema,
        responseSchema: GetAdminTrainProvenanceStationBoardResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceStationBoardTasks: {
        operationName: 'GetAdminTrainProvenanceStationBoardTasks',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/station-board-tasks',
        requestSchema: GetAdminTrainProvenanceStationBoardTasksRequestSchema,
        responseSchema: GetAdminTrainProvenanceStationBoardTasksResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTrainProvenanceStationPlatformRefresh: {
        operationName: 'GetAdminTrainProvenanceStationPlatformRefresh',
        method: 'GET',
        pathTemplate: '/api/v2/admin/train-provenance/station-platform-refresh',
        requestSchema:
            GetAdminTrainProvenanceStationPlatformRefreshRequestSchema,
        responseSchema:
            GetAdminTrainProvenanceStationPlatformRefreshResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    }
} satisfies Record<string, V2ClientOperation>;

export const GetAdminTrainProvenance =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenance;
export const GetAdminTrainProvenanceCouplingScan =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceCouplingScan;
export const GetAdminTrainProvenanceCouplingScanTasks =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceCouplingScanTasks;
export const GetAdminTrainProvenanceQrcodeScan =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceQrcodeScan;
export const GetAdminTrainProvenanceQrcodeScanTasks =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceQrcodeScanTasks;
export const GetAdminTrainProvenanceRequestStats =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceRequestStats;
export const GetAdminTrainProvenanceStationBoard =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceStationBoard;
export const GetAdminTrainProvenanceStationBoardTasks =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceStationBoardTasks;
export const GetAdminTrainProvenanceStationPlatformRefresh =
    ADMINPROVENANCE_V2_OPERATIONS.GetAdminTrainProvenanceStationPlatformRefresh;
