// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    DeleteAdminQqBanEntryRequestSchema,
    DeleteAdminQqBanEntryResponseSchema,
    DeleteAdminUserMembershipRequestSchema,
    DeleteAdminUserMembershipResponseSchema,
    GetAdminUserMembershipsRequestSchema,
    GetAdminUserMembershipsResponseSchema,
    GetAdminUsersRequestSchema,
    GetAdminUsersResponseSchema,
    GetAdminUsersSecurityRequestSchema,
    GetAdminUsersSecurityResponseSchema,
    PostAdminQqBanEntryRequestSchema,
    PostAdminQqBanEntryResponseSchema,
    PostAdminUsersQuotaResetRequestSchema,
    PostAdminUsersQuotaResetResponseSchema,
    PostAdminUsersRiskClearRequestSchema,
    PostAdminUsersRiskClearResponseSchema,
    PostAdminUsersStatusRequestSchema,
    PostAdminUsersStatusResponseSchema,
    PutAdminUserMembershipRequestSchema,
    PutAdminUserMembershipResponseSchema
} from '#shared/generated/proto/opencrh/v2/admin_users_pb';
import type { V2ClientOperation } from './types';

export const ADMINUSERS_V2_OPERATIONS = {
    GetAdminUsers: {
        operationName: 'GetAdminUsers',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users',
        requestSchema: GetAdminUsersRequestSchema,
        responseSchema: GetAdminUsersResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    GetAdminUserMemberships: {
        operationName: 'GetAdminUserMemberships',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users/:userId/memberships',
        requestSchema: GetAdminUserMembershipsRequestSchema,
        responseSchema: GetAdminUserMembershipsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PutAdminUserMembership: {
        operationName: 'PutAdminUserMembership',
        method: 'PUT',
        pathTemplate: '/api/v2/admin/users/:userId/memberships/:groupId',
        requestSchema: PutAdminUserMembershipRequestSchema,
        responseSchema: PutAdminUserMembershipResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    },
    DeleteAdminUserMembership: {
        operationName: 'DeleteAdminUserMembership',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/users/:userId/memberships/:groupId',
        requestSchema: DeleteAdminUserMembershipRequestSchema,
        responseSchema: DeleteAdminUserMembershipResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PostAdminQqBanEntry: {
        operationName: 'PostAdminQqBanEntry',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/qq-ban-list',
        requestSchema: PostAdminQqBanEntryRequestSchema,
        responseSchema: PostAdminQqBanEntryResponseSchema,
        bodyMode: 'required',
        responseKind: 'protobuf',
    },
    DeleteAdminQqBanEntry: {
        operationName: 'DeleteAdminQqBanEntry',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/users/qq-ban-list/:qqNumber',
        requestSchema: DeleteAdminQqBanEntryRequestSchema,
        responseSchema: DeleteAdminQqBanEntryResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PostAdminUsersQuotaReset: {
        operationName: 'PostAdminUsersQuotaReset',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/quota/reset',
        requestSchema: PostAdminUsersQuotaResetRequestSchema,
        responseSchema: PostAdminUsersQuotaResetResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    },
    PostAdminUsersRiskClear: {
        operationName: 'PostAdminUsersRiskClear',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/risk/clear',
        requestSchema: PostAdminUsersRiskClearRequestSchema,
        responseSchema: PostAdminUsersRiskClearResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    },
    GetAdminUsersSecurity: {
        operationName: 'GetAdminUsersSecurity',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users/security',
        requestSchema: GetAdminUsersSecurityRequestSchema,
        responseSchema: GetAdminUsersSecurityResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PostAdminUsersStatus: {
        operationName: 'PostAdminUsersStatus',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/status',
        requestSchema: PostAdminUsersStatusRequestSchema,
        responseSchema: PostAdminUsersStatusResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    }
} satisfies Record<string, V2ClientOperation>;

export const GetAdminUsers = ADMINUSERS_V2_OPERATIONS.GetAdminUsers;
export const GetAdminUserMemberships = ADMINUSERS_V2_OPERATIONS.GetAdminUserMemberships;
export const PutAdminUserMembership = ADMINUSERS_V2_OPERATIONS.PutAdminUserMembership;
export const DeleteAdminUserMembership = ADMINUSERS_V2_OPERATIONS.DeleteAdminUserMembership;
export const PostAdminQqBanEntry = ADMINUSERS_V2_OPERATIONS.PostAdminQqBanEntry;
export const DeleteAdminQqBanEntry = ADMINUSERS_V2_OPERATIONS.DeleteAdminQqBanEntry;
export const PostAdminUsersQuotaReset = ADMINUSERS_V2_OPERATIONS.PostAdminUsersQuotaReset;
export const PostAdminUsersRiskClear = ADMINUSERS_V2_OPERATIONS.PostAdminUsersRiskClear;
export const GetAdminUsersSecurity = ADMINUSERS_V2_OPERATIONS.GetAdminUsersSecurity;
export const PostAdminUsersStatus = ADMINUSERS_V2_OPERATIONS.PostAdminUsersStatus;
