// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    DeleteAdminDailyRouteRequestSchema,
    DeleteAdminDailyRouteResponseSchema,
    DeleteAdminOfficialCirculationRequestSchema,
    DeleteAdminOfficialCirculationResponseSchema,
    DeleteAdminTimetableHistoryCoverageRequestSchema,
    DeleteAdminTimetableHistoryCoverageResponseSchema,
    GetAdminAnomalyScanRequestSchema,
    GetAdminAnomalyScanResponseSchema,
    GetAdminConfigFileRequestSchema,
    GetAdminConfigFileResponseSchema,
    GetAdminConfigFilesRequestSchema,
    GetAdminConfigFilesResponseSchema,
    GetAdminDailyRoutesRequestSchema,
    GetAdminDailyRoutesResponseSchema,
    GetAdminDailyRoutesTimetablesRequestSchema,
    GetAdminDailyRoutesTimetablesResponseSchema,
    GetAdminMembershipCodesRequestSchema,
    GetAdminMembershipCodesResponseSchema,
    GetAdminOauthClientsRequestSchema,
    GetAdminOauthClientsResponseSchema,
    GetAdminOfficialCirculationsRequestSchema,
    GetAdminOfficialCirculationsResponseSchema,
    GetAdminPassiveAlertsRequestSchema,
    GetAdminPassiveAlertsResponseSchema,
    GetAdminServerMetricsRequestSchema,
    GetAdminServerMetricsResponseSchema,
    GetAdminTasksRequestSchema,
    GetAdminTasksResponseSchema,
    GetAdminTimetableHistoryMergeCandidatesRequestSchema,
    GetAdminTimetableHistoryMergeCandidatesResponseSchema,
    GetAdminTrafficRequestSchema,
    GetAdminTrafficResponseSchema,
    PatchAdminOauthClientRequestSchema,
    PatchAdminOauthClientResponseSchema,
    PostAdminAnomalyDeleteByTypeRequestSchema,
    PostAdminAnomalyDeleteByTypeResponseSchema,
    PostAdminAnomalyDeleteRouteRequestSchema,
    PostAdminAnomalyDeleteRouteResponseSchema,
    PostAdminConfigFilesRequestSchema,
    PostAdminConfigFilesResponseSchema,
    PostAdminDailyRoutesRequestSchema,
    PostAdminDailyRoutesResponseSchema,
    PostAdminMembershipCodesRequestSchema,
    PostAdminMembershipCodesResponseSchema,
    PostAdminOauthClientRevokeTokensRequestSchema,
    PostAdminOauthClientRevokeTokensResponseSchema,
    PostAdminTasksRequestSchema,
    PostAdminTasksResponseSchema,
    PostAdminWebappTokensRevokeAllRequestSchema,
    PostAdminWebappTokensRevokeAllResponseSchema,
    PutAdminConfigFileRequestSchema,
    PutAdminConfigFileResponseSchema
} from '#shared/generated/proto/opencrh/v2/admin_pb';
import type { V2ClientOperation } from './types';

export const ADMIN_V2_OPERATIONS = {
    PostAdminAnomalyDeleteByType: {
        operationName: 'PostAdminAnomalyDeleteByType',
        method: 'POST',
        pathTemplate: '/api/v2/admin/anomaly-actions/delete-by-type',
        requestSchema: PostAdminAnomalyDeleteByTypeRequestSchema,
        responseSchema: PostAdminAnomalyDeleteByTypeResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    PostAdminAnomalyDeleteRoute: {
        operationName: 'PostAdminAnomalyDeleteRoute',
        method: 'POST',
        pathTemplate: '/api/v2/admin/anomaly-actions/delete-route',
        requestSchema: PostAdminAnomalyDeleteRouteRequestSchema,
        responseSchema: PostAdminAnomalyDeleteRouteResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetAdminAnomalyScan: {
        operationName: 'GetAdminAnomalyScan',
        method: 'GET',
        pathTemplate: '/api/v2/admin/anomaly-scan',
        requestSchema: GetAdminAnomalyScanRequestSchema,
        responseSchema: GetAdminAnomalyScanResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminConfigFiles: {
        operationName: 'GetAdminConfigFiles',
        method: 'GET',
        pathTemplate: '/api/v2/admin/config-files',
        requestSchema: GetAdminConfigFilesRequestSchema,
        responseSchema: GetAdminConfigFilesResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostAdminConfigFiles: {
        operationName: 'PostAdminConfigFiles',
        method: 'POST',
        pathTemplate: '/api/v2/admin/config-files',
        requestSchema: PostAdminConfigFilesRequestSchema,
        responseSchema: PostAdminConfigFilesResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetAdminConfigFile: {
        operationName: 'GetAdminConfigFile',
        method: 'GET',
        pathTemplate: '/api/v2/admin/config-files/:target',
        requestSchema: GetAdminConfigFileRequestSchema,
        responseSchema: GetAdminConfigFileResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PutAdminConfigFile: {
        operationName: 'PutAdminConfigFile',
        method: 'PUT',
        pathTemplate: '/api/v2/admin/config-files/:target',
        requestSchema: PutAdminConfigFileRequestSchema,
        responseSchema: PutAdminConfigFileResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetAdminDailyRoutes: {
        operationName: 'GetAdminDailyRoutes',
        method: 'GET',
        pathTemplate: '/api/v2/admin/daily-routes',
        requestSchema: GetAdminDailyRoutesRequestSchema,
        responseSchema: GetAdminDailyRoutesResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostAdminDailyRoutes: {
        operationName: 'PostAdminDailyRoutes',
        method: 'POST',
        pathTemplate: '/api/v2/admin/daily-routes',
        requestSchema: PostAdminDailyRoutesRequestSchema,
        responseSchema: PostAdminDailyRoutesResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    DeleteAdminDailyRoute: {
        operationName: 'DeleteAdminDailyRoute',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/daily-routes/:id',
        requestSchema: DeleteAdminDailyRouteRequestSchema,
        responseSchema: DeleteAdminDailyRouteResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminDailyRoutesTimetables: {
        operationName: 'GetAdminDailyRoutesTimetables',
        method: 'GET',
        pathTemplate: '/api/v2/admin/daily-routes/timetables',
        requestSchema: GetAdminDailyRoutesTimetablesRequestSchema,
        responseSchema: GetAdminDailyRoutesTimetablesResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminMembershipCodes: {
        operationName: 'GetAdminMembershipCodes',
        method: 'GET',
        pathTemplate: '/api/v2/admin/membership-codes',
        requestSchema: GetAdminMembershipCodesRequestSchema,
        responseSchema: GetAdminMembershipCodesResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostAdminMembershipCodes: {
        operationName: 'PostAdminMembershipCodes',
        method: 'POST',
        pathTemplate: '/api/v2/admin/membership-codes',
        requestSchema: PostAdminMembershipCodesRequestSchema,
        responseSchema: PostAdminMembershipCodesResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetAdminOauthClients: {
        operationName: 'GetAdminOauthClients',
        method: 'GET',
        pathTemplate: '/api/v2/admin/oauth/clients',
        requestSchema: GetAdminOauthClientsRequestSchema,
        responseSchema: GetAdminOauthClientsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PatchAdminOauthClient: {
        operationName: 'PatchAdminOauthClient',
        method: 'PATCH',
        pathTemplate: '/api/v2/admin/oauth/clients/:clientId',
        requestSchema: PatchAdminOauthClientRequestSchema,
        responseSchema: PatchAdminOauthClientResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    PostAdminOauthClientRevokeTokens: {
        operationName: 'PostAdminOauthClientRevokeTokens',
        method: 'POST',
        pathTemplate: '/api/v2/admin/oauth/clients/:clientId/revoke-tokens',
        requestSchema: PostAdminOauthClientRevokeTokensRequestSchema,
        responseSchema: PostAdminOauthClientRevokeTokensResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminOfficialCirculations: {
        operationName: 'GetAdminOfficialCirculations',
        method: 'GET',
        pathTemplate: '/api/v2/admin/official-circulations',
        requestSchema: GetAdminOfficialCirculationsRequestSchema,
        responseSchema: GetAdminOfficialCirculationsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    DeleteAdminOfficialCirculation: {
        operationName: 'DeleteAdminOfficialCirculation',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/official-circulations/:entryKey',
        requestSchema: DeleteAdminOfficialCirculationRequestSchema,
        responseSchema: DeleteAdminOfficialCirculationResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminPassiveAlerts: {
        operationName: 'GetAdminPassiveAlerts',
        method: 'GET',
        pathTemplate: '/api/v2/admin/passive-alerts',
        requestSchema: GetAdminPassiveAlertsRequestSchema,
        responseSchema: GetAdminPassiveAlertsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminServerMetrics: {
        operationName: 'GetAdminServerMetrics',
        method: 'GET',
        pathTemplate: '/api/v2/admin/server-metrics',
        requestSchema: GetAdminServerMetricsRequestSchema,
        responseSchema: GetAdminServerMetricsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTasks: {
        operationName: 'GetAdminTasks',
        method: 'GET',
        pathTemplate: '/api/v2/admin/tasks',
        requestSchema: GetAdminTasksRequestSchema,
        responseSchema: GetAdminTasksResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostAdminTasks: {
        operationName: 'PostAdminTasks',
        method: 'POST',
        pathTemplate: '/api/v2/admin/tasks',
        requestSchema: PostAdminTasksRequestSchema,
        responseSchema: PostAdminTasksResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetAdminTimetableHistoryMergeCandidates: {
        operationName: 'GetAdminTimetableHistoryMergeCandidates',
        method: 'GET',
        pathTemplate: '/api/v2/admin/timetable-history/merge-candidates',
        requestSchema: GetAdminTimetableHistoryMergeCandidatesRequestSchema,
        responseSchema: GetAdminTimetableHistoryMergeCandidatesResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    DeleteAdminTimetableHistoryCoverage: {
        operationName: 'DeleteAdminTimetableHistoryCoverage',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/timetable-history/coverages/:coverageId',
        requestSchema: DeleteAdminTimetableHistoryCoverageRequestSchema,
        responseSchema: DeleteAdminTimetableHistoryCoverageResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetAdminTraffic: {
        operationName: 'GetAdminTraffic',
        method: 'GET',
        pathTemplate: '/api/v2/admin/traffic',
        requestSchema: GetAdminTrafficRequestSchema,
        responseSchema: GetAdminTrafficResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostAdminWebappTokensRevokeAll: {
        operationName: 'PostAdminWebappTokensRevokeAll',
        method: 'POST',
        pathTemplate: '/api/v2/admin/webapp-tokens/revoke-all',
        requestSchema: PostAdminWebappTokensRevokeAllRequestSchema,
        responseSchema: PostAdminWebappTokensRevokeAllResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    }
} satisfies Record<string, V2ClientOperation>;

export const PostAdminAnomalyDeleteByType =
    ADMIN_V2_OPERATIONS.PostAdminAnomalyDeleteByType;
export const PostAdminAnomalyDeleteRoute =
    ADMIN_V2_OPERATIONS.PostAdminAnomalyDeleteRoute;
export const GetAdminAnomalyScan = ADMIN_V2_OPERATIONS.GetAdminAnomalyScan;
export const GetAdminConfigFiles = ADMIN_V2_OPERATIONS.GetAdminConfigFiles;
export const PostAdminConfigFiles = ADMIN_V2_OPERATIONS.PostAdminConfigFiles;
export const GetAdminConfigFile = ADMIN_V2_OPERATIONS.GetAdminConfigFile;
export const PutAdminConfigFile = ADMIN_V2_OPERATIONS.PutAdminConfigFile;
export const GetAdminDailyRoutes = ADMIN_V2_OPERATIONS.GetAdminDailyRoutes;
export const PostAdminDailyRoutes = ADMIN_V2_OPERATIONS.PostAdminDailyRoutes;
export const DeleteAdminDailyRoute = ADMIN_V2_OPERATIONS.DeleteAdminDailyRoute;
export const GetAdminDailyRoutesTimetables =
    ADMIN_V2_OPERATIONS.GetAdminDailyRoutesTimetables;
export const GetAdminMembershipCodes =
    ADMIN_V2_OPERATIONS.GetAdminMembershipCodes;
export const PostAdminMembershipCodes =
    ADMIN_V2_OPERATIONS.PostAdminMembershipCodes;
export const GetAdminOauthClients = ADMIN_V2_OPERATIONS.GetAdminOauthClients;
export const PatchAdminOauthClient = ADMIN_V2_OPERATIONS.PatchAdminOauthClient;
export const PostAdminOauthClientRevokeTokens =
    ADMIN_V2_OPERATIONS.PostAdminOauthClientRevokeTokens;
export const GetAdminOfficialCirculations =
    ADMIN_V2_OPERATIONS.GetAdminOfficialCirculations;
export const DeleteAdminOfficialCirculation =
    ADMIN_V2_OPERATIONS.DeleteAdminOfficialCirculation;
export const GetAdminPassiveAlerts = ADMIN_V2_OPERATIONS.GetAdminPassiveAlerts;
export const GetAdminServerMetrics = ADMIN_V2_OPERATIONS.GetAdminServerMetrics;
export const GetAdminTasks = ADMIN_V2_OPERATIONS.GetAdminTasks;
export const PostAdminTasks = ADMIN_V2_OPERATIONS.PostAdminTasks;
export const GetAdminTimetableHistoryMergeCandidates =
    ADMIN_V2_OPERATIONS.GetAdminTimetableHistoryMergeCandidates;
export const DeleteAdminTimetableHistoryCoverage =
    ADMIN_V2_OPERATIONS.DeleteAdminTimetableHistoryCoverage;
export const GetAdminTraffic = ADMIN_V2_OPERATIONS.GetAdminTraffic;
export const PostAdminWebappTokensRevokeAll =
    ADMIN_V2_OPERATIONS.PostAdminWebappTokensRevokeAll;
