// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    GetDailyExportIndexRequestSchema,
    GetDailyExportIndexResponseSchema,
    GetDailyExportRequestSchema,
    GetDailyExportResponseSchema
} from '#shared/generated/proto/opencrh/v2/exports_pb';
import type { V2ClientOperation } from './types';

export const EXPORTS_V2_OPERATIONS = {
    GetDailyExportIndex: {
        operationName: 'GetDailyExportIndex',
        method: 'GET',
        pathTemplate: '/api/v2/exports/daily/index',
        requestSchema: GetDailyExportIndexRequestSchema,
        responseSchema: GetDailyExportIndexResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetDailyExport: {
        operationName: 'GetDailyExport',
        method: 'GET',
        pathTemplate: '/api/v2/exports/daily/:date',
        requestSchema: GetDailyExportRequestSchema,
        responseSchema: GetDailyExportResponseSchema,
        bodyMode: 'none',
        responseKind: 'raw',
        rawContentTypes: ['text/csv']
    }
} satisfies Record<string, V2ClientOperation>;

export const GetDailyExportIndex = EXPORTS_V2_OPERATIONS.GetDailyExportIndex;
export const GetDailyExport = EXPORTS_V2_OPERATIONS.GetDailyExport;
