// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    DeleteFeedbackTopicRequestSchema,
    DeleteFeedbackTopicResponseSchema,
    GetFeedbackTopicRequestSchema,
    GetFeedbackTopicResponseSchema,
    GetFeedbackTopicsRequestSchema,
    GetFeedbackTopicsResponseSchema,
    PatchFeedbackTopicRequestSchema,
    PatchFeedbackTopicResponseSchema,
    PostFeedbackTopicMessageRequestSchema,
    PostFeedbackTopicMessageResponseSchema,
    PostFeedbackTopicsRequestSchema,
    PostFeedbackTopicsResponseSchema
} from '#shared/generated/proto/opencrh/v2/feedback_pb';
import type { V2ClientOperation } from './types';

export const FEEDBACK_V2_OPERATIONS = {
    GetFeedbackTopics: {
        operationName: 'GetFeedbackTopics',
        method: 'GET',
        pathTemplate: '/api/v2/feedback/topics',
        requestSchema: GetFeedbackTopicsRequestSchema,
        responseSchema: GetFeedbackTopicsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PostFeedbackTopics: {
        operationName: 'PostFeedbackTopics',
        method: 'POST',
        pathTemplate: '/api/v2/feedback/topics',
        requestSchema: PostFeedbackTopicsRequestSchema,
        responseSchema: PostFeedbackTopicsResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    },
    GetFeedbackTopic: {
        operationName: 'GetFeedbackTopic',
        method: 'GET',
        pathTemplate: '/api/v2/feedback/topics/:id',
        requestSchema: GetFeedbackTopicRequestSchema,
        responseSchema: GetFeedbackTopicResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PatchFeedbackTopic: {
        operationName: 'PatchFeedbackTopic',
        method: 'PATCH',
        pathTemplate: '/api/v2/feedback/topics/:id',
        requestSchema: PatchFeedbackTopicRequestSchema,
        responseSchema: PatchFeedbackTopicResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    },
    DeleteFeedbackTopic: {
        operationName: 'DeleteFeedbackTopic',
        method: 'DELETE',
        pathTemplate: '/api/v2/feedback/topics/:id',
        requestSchema: DeleteFeedbackTopicRequestSchema,
        responseSchema: DeleteFeedbackTopicResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf',
    },
    PostFeedbackTopicMessage: {
        operationName: 'PostFeedbackTopicMessage',
        method: 'POST',
        pathTemplate: '/api/v2/feedback/topics/:id/messages',
        requestSchema: PostFeedbackTopicMessageRequestSchema,
        responseSchema: PostFeedbackTopicMessageResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf',
    }
} satisfies Record<string, V2ClientOperation>;

export const GetFeedbackTopics = FEEDBACK_V2_OPERATIONS.GetFeedbackTopics;
export const PostFeedbackTopics = FEEDBACK_V2_OPERATIONS.PostFeedbackTopics;
export const GetFeedbackTopic = FEEDBACK_V2_OPERATIONS.GetFeedbackTopic;
export const PatchFeedbackTopic = FEEDBACK_V2_OPERATIONS.PatchFeedbackTopic;
export const DeleteFeedbackTopic = FEEDBACK_V2_OPERATIONS.DeleteFeedbackTopic;
export const PostFeedbackTopicMessage = FEEDBACK_V2_OPERATIONS.PostFeedbackTopicMessage;
