// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import { ADMIN_V2_OPERATIONS } from './admin';
import { ADMINPROVENANCE_V2_OPERATIONS } from './adminProvenance';
import { ADMINUSERS_V2_OPERATIONS } from './adminUsers';
import { AUTH_V2_OPERATIONS } from './auth';
import { EXPORTS_V2_OPERATIONS } from './exports';
import { FEEDBACK_V2_OPERATIONS } from './feedback';
import { LOOKUP_V2_OPERATIONS } from './lookup';
import { NOTIFICATIONS_V2_OPERATIONS } from './notifications';
import { OAUTH_V2_OPERATIONS } from './oauth';
import { SYSTEM_V2_OPERATIONS } from './system';

export const V2_CLIENT_OPERATIONS = {
    ...ADMIN_V2_OPERATIONS,
    ...ADMINPROVENANCE_V2_OPERATIONS,
    ...ADMINUSERS_V2_OPERATIONS,
    ...AUTH_V2_OPERATIONS,
    ...EXPORTS_V2_OPERATIONS,
    ...FEEDBACK_V2_OPERATIONS,
    ...LOOKUP_V2_OPERATIONS,
    ...NOTIFICATIONS_V2_OPERATIONS,
    ...OAUTH_V2_OPERATIONS,
    ...SYSTEM_V2_OPERATIONS,
} as const;

export type V2ClientOperationName = keyof typeof V2_CLIENT_OPERATIONS;
