// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    GetCurrentTrainTimetableRequestSchema,
    GetCurrentTrainTimetableResponseSchema,
    GetDailyRecordsRequestSchema,
    GetDailyRecordsResponseSchema,
    GetEmuAllocationRequestSchema,
    GetEmuAllocationResponseSchema,
    GetEmuHistoryRequestSchema,
    GetEmuHistoryResponseSchema,
    GetSearchIndexRequestSchema,
    GetSearchIndexResponseSchema,
    GetStationTimetableRequestSchema,
    GetStationTimetableResponseSchema,
    GetTrainHistoryRequestSchema,
    GetTrainHistoryResponseSchema
} from '#shared/generated/proto/opencrh/v2/lookup_pb';
import {
    GetTrainCirculationImageRequestSchema,
    GetTrainCirculationImageResponseSchema,
    GetTrainTimetableHistoryRequestSchema,
    GetTrainTimetableHistoryResponseSchema
} from '#shared/generated/proto/opencrh/v2/timetable_pb';
import type { V2ClientOperation } from './types';

export const LOOKUP_V2_OPERATIONS = {
    GetEmuAllocation: {
        operationName: 'GetEmuAllocation',
        method: 'GET',
        pathTemplate: '/api/v2/allocation/emu/:emuCode',
        requestSchema: GetEmuAllocationRequestSchema,
        responseSchema: GetEmuAllocationResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetSearchIndex: {
        operationName: 'GetSearchIndex',
        method: 'GET',
        pathTemplate: '/api/v2/search/index',
        requestSchema: GetSearchIndexRequestSchema,
        responseSchema: GetSearchIndexResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetCurrentTrainTimetable: {
        operationName: 'GetCurrentTrainTimetable',
        method: 'GET',
        pathTemplate: '/api/v2/timetable/train/:trainCode/current',
        requestSchema: GetCurrentTrainTimetableRequestSchema,
        responseSchema: GetCurrentTrainTimetableResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetStationTimetable: {
        operationName: 'GetStationTimetable',
        method: 'GET',
        pathTemplate: '/api/v2/timetable/station/:stationName',
        requestSchema: GetStationTimetableRequestSchema,
        responseSchema: GetStationTimetableResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetDailyRecords: {
        operationName: 'GetDailyRecords',
        method: 'GET',
        pathTemplate: '/api/v2/records/daily',
        requestSchema: GetDailyRecordsRequestSchema,
        responseSchema: GetDailyRecordsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetTrainHistory: {
        operationName: 'GetTrainHistory',
        method: 'GET',
        pathTemplate: '/api/v2/history/train/:trainCode',
        requestSchema: GetTrainHistoryRequestSchema,
        responseSchema: GetTrainHistoryResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetEmuHistory: {
        operationName: 'GetEmuHistory',
        method: 'GET',
        pathTemplate: '/api/v2/history/emu/:emuCode',
        requestSchema: GetEmuHistoryRequestSchema,
        responseSchema: GetEmuHistoryResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetTrainTimetableHistory: {
        operationName: 'GetTrainTimetableHistory',
        method: 'GET',
        pathTemplate: '/api/v2/timetable/train/:trainCode/history',
        requestSchema: GetTrainTimetableHistoryRequestSchema,
        responseSchema: GetTrainTimetableHistoryResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetTrainCirculationImage: {
        operationName: 'GetTrainCirculationImage',
        method: 'GET',
        pathTemplate: '/api/v2/timetable/train/:trainCode/circulation/image',
        requestSchema: GetTrainCirculationImageRequestSchema,
        responseSchema: GetTrainCirculationImageResponseSchema,
        bodyMode: 'none',
        responseKind: 'raw',
        rawContentTypes: ['image/png', 'application/pdf']
    }
} satisfies Record<string, V2ClientOperation>;

export const GetEmuAllocation = LOOKUP_V2_OPERATIONS.GetEmuAllocation;
export const GetSearchIndex = LOOKUP_V2_OPERATIONS.GetSearchIndex;
export const GetCurrentTrainTimetable =
    LOOKUP_V2_OPERATIONS.GetCurrentTrainTimetable;
export const GetStationTimetable = LOOKUP_V2_OPERATIONS.GetStationTimetable;
export const GetDailyRecords = LOOKUP_V2_OPERATIONS.GetDailyRecords;
export const GetTrainHistory = LOOKUP_V2_OPERATIONS.GetTrainHistory;
export const GetEmuHistory = LOOKUP_V2_OPERATIONS.GetEmuHistory;
export const GetTrainTimetableHistory =
    LOOKUP_V2_OPERATIONS.GetTrainTimetableHistory;
export const GetTrainCirculationImage =
    LOOKUP_V2_OPERATIONS.GetTrainCirculationImage;
