// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    PostNotificationsSendRequestSchema,
    PostNotificationsSendResponseSchema
} from '#shared/generated/proto/opencrh/v2/notifications_pb';
import type { V2ClientOperation } from './types';

export const NOTIFICATIONS_V2_OPERATIONS = {
    PostNotificationsSend: {
        operationName: 'PostNotificationsSend',
        method: 'POST',
        pathTemplate: '/api/v2/notifications/send',
        requestSchema: PostNotificationsSendRequestSchema,
        responseSchema: PostNotificationsSendResponseSchema,
        bodyMode: 'required',
        responseKind: 'protobuf'
    }
} satisfies Record<string, V2ClientOperation>;

export const PostNotificationsSend =
    NOTIFICATIONS_V2_OPERATIONS.PostNotificationsSend;
