// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    DeleteOauthClientRequestSchema,
    DeleteOauthClientResponseSchema,
    GetOauthAuthorizeContextRequestSchema,
    GetOauthAuthorizeContextResponseSchema,
    GetOauthClientRequestSchema,
    GetOauthClientResponseSchema,
    GetOauthClientsRequestSchema,
    GetOauthClientsResponseSchema,
    PatchOauthClientRequestSchema,
    PatchOauthClientResponseSchema,
    PostOauthClientsRequestSchema,
    PostOauthClientsResponseSchema
} from '#shared/generated/proto/opencrh/v2/oauth_pb';
import type { V2ClientOperation } from './types';

export const OAUTH_V2_OPERATIONS = {
    GetOauthAuthorizeContext: {
        operationName: 'GetOauthAuthorizeContext',
        method: 'GET',
        pathTemplate: '/api/v2/oauth/authorize/context',
        requestSchema: GetOauthAuthorizeContextRequestSchema,
        responseSchema: GetOauthAuthorizeContextResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetOauthClients: {
        operationName: 'GetOauthClients',
        method: 'GET',
        pathTemplate: '/api/v2/oauth/clients',
        requestSchema: GetOauthClientsRequestSchema,
        responseSchema: GetOauthClientsResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PostOauthClients: {
        operationName: 'PostOauthClients',
        method: 'POST',
        pathTemplate: '/api/v2/oauth/clients',
        requestSchema: PostOauthClientsRequestSchema,
        responseSchema: PostOauthClientsResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    GetOauthClient: {
        operationName: 'GetOauthClient',
        method: 'GET',
        pathTemplate: '/api/v2/oauth/clients/:clientId',
        requestSchema: GetOauthClientRequestSchema,
        responseSchema: GetOauthClientResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    PatchOauthClient: {
        operationName: 'PatchOauthClient',
        method: 'PATCH',
        pathTemplate: '/api/v2/oauth/clients/:clientId',
        requestSchema: PatchOauthClientRequestSchema,
        responseSchema: PatchOauthClientResponseSchema,
        bodyMode: 'optional',
        responseKind: 'protobuf'
    },
    DeleteOauthClient: {
        operationName: 'DeleteOauthClient',
        method: 'DELETE',
        pathTemplate: '/api/v2/oauth/clients/:clientId',
        requestSchema: DeleteOauthClientRequestSchema,
        responseSchema: DeleteOauthClientResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    }
} satisfies Record<string, V2ClientOperation>;

export const GetOauthAuthorizeContext =
    OAUTH_V2_OPERATIONS.GetOauthAuthorizeContext;
export const GetOauthClients = OAUTH_V2_OPERATIONS.GetOauthClients;
export const PostOauthClients = OAUTH_V2_OPERATIONS.PostOauthClients;
export const GetOauthClient = OAUTH_V2_OPERATIONS.GetOauthClient;
export const PatchOauthClient = OAUTH_V2_OPERATIONS.PatchOauthClient;
export const DeleteOauthClient = OAUTH_V2_OPERATIONS.DeleteOauthClient;
