// Generated by scripts/generate-v2-client-registry.mjs. Do not edit manually.
import {
    GetDebugEchoErrorRequestSchema,
    GetDebugEchoErrorResponseSchema,
    GetExposedConfigRequestSchema,
    GetExposedConfigResponseSchema,
    GetHealthRequestSchema,
    GetHealthResponseSchema
} from '#shared/generated/proto/opencrh/v2/system_pb';
import type { V2ClientOperation } from './types';

export const SYSTEM_V2_OPERATIONS = {
    GetHealth: {
        operationName: 'GetHealth',
        method: 'GET',
        pathTemplate: '/api/v2/health',
        requestSchema: GetHealthRequestSchema,
        responseSchema: GetHealthResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetDebugEchoError: {
        operationName: 'GetDebugEchoError',
        method: 'GET',
        pathTemplate: '/api/v2/debug/echo-error',
        requestSchema: GetDebugEchoErrorRequestSchema,
        responseSchema: GetDebugEchoErrorResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    },
    GetExposedConfig: {
        operationName: 'GetExposedConfig',
        method: 'GET',
        pathTemplate: '/api/v2/exposed-config',
        requestSchema: GetExposedConfigRequestSchema,
        responseSchema: GetExposedConfigResponseSchema,
        bodyMode: 'none',
        responseKind: 'protobuf'
    }
} satisfies Record<string, V2ClientOperation>;

export const GetHealth = SYSTEM_V2_OPERATIONS.GetHealth;
export const GetDebugEchoError = SYSTEM_V2_OPERATIONS.GetDebugEchoError;
export const GetExposedConfig = SYSTEM_V2_OPERATIONS.GetExposedConfig;
