import { defineV2Operation } from '~/server/utils/api/v2/V2Types';
import {
    DeleteAdminQqBanEntryRequestSchema,
    DeleteAdminQqBanEntryDataSchema,
    DeleteAdminQqBanEntryResponseSchema,
    DeleteAdminUserMembershipRequestSchema,
    DeleteAdminUserMembershipDataSchema,
    DeleteAdminUserMembershipResponseSchema,
    GetAdminUserMembershipsRequestSchema,
    GetAdminUserMembershipsDataSchema,
    GetAdminUserMembershipsResponseSchema,
    GetAdminUsersRequestSchema,
    GetAdminUsersDataSchema,
    GetAdminUsersResponseSchema,
    GetAdminUsersSecurityRequestSchema,
    GetAdminUsersSecurityDataSchema,
    GetAdminUsersSecurityResponseSchema,
    PostAdminQqBanEntryRequestSchema,
    PostAdminQqBanEntryDataSchema,
    PostAdminQqBanEntryResponseSchema,
    PostAdminUsersQuotaResetRequestSchema,
    PostAdminUsersQuotaResetDataSchema,
    PostAdminUsersQuotaResetResponseSchema,
    PostAdminUsersRiskClearRequestSchema,
    PostAdminUsersRiskClearDataSchema,
    PostAdminUsersRiskClearResponseSchema,
    PostAdminUsersStatusRequestSchema,
    PostAdminUsersStatusDataSchema,
    PostAdminUsersStatusResponseSchema,
    PutAdminUserMembershipRequestSchema,
    PutAdminUserMembershipDataSchema,
    PutAdminUserMembershipResponseSchema
} from '#shared/generated/proto/opencrh/v2/admin_users_pb';
import {
    deleteAdminQqBanEntryV2Adapter,
    deleteAdminUserMembershipV2Adapter,
    getAdminUserMembershipsV2Adapter,
    getAdminUsersSecurityV2Adapter,
    getAdminUsersV2Adapter,
    postAdminQqBanEntryV2Adapter,
    postAdminUsersQuotaResetV2Adapter,
    postAdminUsersRiskClearV2Adapter,
    postAdminUsersStatusV2Adapter,
    putAdminUserMembershipV2Adapter
} from '~/server/utils/api/v2/adapters/adminUsers';
import { API_SCOPES } from '~/server/utils/api/scopes/apiScopes';

export const ADMIN_USERS_MANIFEST_ENTRIES = {
    GetAdminUsers: defineV2Operation({
        operationName: 'GetAdminUsers',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users',
        requestSchema: GetAdminUsersRequestSchema,
        dataSchema: GetAdminUsersDataSchema,
        responseSchema: GetAdminUsersResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: true,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: getAdminUsersV2Adapter
    }),
    GetAdminUserMemberships: defineV2Operation({
        operationName: 'GetAdminUserMemberships',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users/:userId/memberships',
        requestSchema: GetAdminUserMembershipsRequestSchema,
        dataSchema: GetAdminUserMembershipsDataSchema,
        responseSchema: GetAdminUserMembershipsResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: getAdminUserMembershipsV2Adapter
    }),
    PutAdminUserMembership: defineV2Operation({
        operationName: 'PutAdminUserMembership',
        method: 'PUT',
        pathTemplate: '/api/v2/admin/users/:userId/memberships/:groupId',
        requestSchema: PutAdminUserMembershipRequestSchema,
        dataSchema: PutAdminUserMembershipDataSchema,
        responseSchema: PutAdminUserMembershipResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        handler: putAdminUserMembershipV2Adapter
    }),
    DeleteAdminUserMembership: defineV2Operation({
        operationName: 'DeleteAdminUserMembership',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/users/:userId/memberships/:groupId',
        requestSchema: DeleteAdminUserMembershipRequestSchema,
        dataSchema: DeleteAdminUserMembershipDataSchema,
        responseSchema: DeleteAdminUserMembershipResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: deleteAdminUserMembershipV2Adapter
    }),
    PostAdminQqBanEntry: defineV2Operation({
        operationName: 'PostAdminQqBanEntry',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/qq-ban-list',
        requestSchema: PostAdminQqBanEntryRequestSchema,
        dataSchema: PostAdminQqBanEntryDataSchema,
        responseSchema: PostAdminQqBanEntryResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'required',
        handler: postAdminQqBanEntryV2Adapter
    }),
    DeleteAdminQqBanEntry: defineV2Operation({
        operationName: 'DeleteAdminQqBanEntry',
        method: 'DELETE',
        pathTemplate: '/api/v2/admin/users/qq-ban-list/:qqNumber',
        requestSchema: DeleteAdminQqBanEntryRequestSchema,
        dataSchema: DeleteAdminQqBanEntryDataSchema,
        responseSchema: DeleteAdminQqBanEntryResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: deleteAdminQqBanEntryV2Adapter
    }),
    PostAdminUsersQuotaReset: defineV2Operation({
        operationName: 'PostAdminUsersQuotaReset',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/quota/reset',
        requestSchema: PostAdminUsersQuotaResetRequestSchema,
        dataSchema: PostAdminUsersQuotaResetDataSchema,
        responseSchema: PostAdminUsersQuotaResetResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        handler: postAdminUsersQuotaResetV2Adapter
    }),
    PostAdminUsersRiskClear: defineV2Operation({
        operationName: 'PostAdminUsersRiskClear',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/risk/clear',
        requestSchema: PostAdminUsersRiskClearRequestSchema,
        dataSchema: PostAdminUsersRiskClearDataSchema,
        responseSchema: PostAdminUsersRiskClearResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        handler: postAdminUsersRiskClearV2Adapter
    }),
    GetAdminUsersSecurity: defineV2Operation({
        operationName: 'GetAdminUsersSecurity',
        method: 'GET',
        pathTemplate: '/api/v2/admin/users/security',
        requestSchema: GetAdminUsersSecurityRequestSchema,
        dataSchema: GetAdminUsersSecurityDataSchema,
        responseSchema: GetAdminUsersSecurityResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: true,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: getAdminUsersSecurityV2Adapter
    }),
    PostAdminUsersStatus: defineV2Operation({
        operationName: 'PostAdminUsersStatus',
        method: 'POST',
        pathTemplate: '/api/v2/admin/users/status',
        requestSchema: PostAdminUsersStatusRequestSchema,
        dataSchema: PostAdminUsersStatusDataSchema,
        responseSchema: PostAdminUsersStatusResponseSchema,
        requiredScopes: [API_SCOPES.admin],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        handler: postAdminUsersStatusV2Adapter
    })
} as const;
