import { defineV2Operation } from '~/server/utils/api/v2/V2Types';
import {
    DeleteAuthApiKeyRequestSchema,
    DeleteAuthApiKeyDataSchema,
    DeleteAuthApiKeyResponseSchema,
    DeleteAuthAuthorizationRequestSchema,
    DeleteAuthAuthorizationDataSchema,
    DeleteAuthAuthorizationResponseSchema,
    DeleteAuthEventSubscriptionsRequestSchema,
    DeleteAuthEventSubscriptionsDataSchema,
    DeleteAuthEventSubscriptionsResponseSchema,
    DeleteAuthFavoritesRequestSchema,
    DeleteAuthFavoritesDataSchema,
    DeleteAuthFavoritesResponseSchema,
    DeleteAuthSubscriptionRequestSchema,
    DeleteAuthSubscriptionDataSchema,
    DeleteAuthSubscriptionResponseSchema,
    GetAuthApiKeysRequestSchema,
    GetAuthApiKeysDataSchema,
    GetAuthApiKeysResponseSchema,
    GetAuthAuthorizationsRequestSchema,
    GetAuthAuthorizationsDataSchema,
    GetAuthAuthorizationsResponseSchema,
    GetAuthEventSubscriptionsRequestSchema,
    GetAuthEventSubscriptionsDataSchema,
    GetAuthEventSubscriptionsResponseSchema,
    GetAuthFavoritesRequestSchema,
    GetAuthFavoritesDataSchema,
    GetAuthFavoritesResponseSchema,
    GetAuthMeRequestSchema,
    GetAuthMeDataSchema,
    GetAuthMeResponseSchema,
    GetAuthMembershipsRequestSchema,
    GetAuthMembershipsDataSchema,
    GetAuthMembershipsResponseSchema,
    GetAuthSettingsRequestSchema,
    GetAuthSettingsDataSchema,
    GetAuthSettingsResponseSchema,
    GetAuthSubscriptionsRequestSchema,
    GetAuthSubscriptionsDataSchema,
    GetAuthSubscriptionsResponseSchema,
    PatchAuthPasswordRequestSchema,
    PatchAuthPasswordDataSchema,
    PatchAuthPasswordResponseSchema,
    PatchAuthSettingsRequestSchema,
    PatchAuthSettingsDataSchema,
    PatchAuthSettingsResponseSchema,
    PatchAuthSubscriptionRequestSchema,
    PatchAuthSubscriptionDataSchema,
    PatchAuthSubscriptionResponseSchema,
    PostAuthApiKeysRequestSchema,
    PostAuthApiKeysDataSchema,
    PostAuthApiKeysResponseSchema,
    PostAuthLoginRequestSchema,
    PostAuthLoginDataSchema,
    PostAuthLoginResponseSchema,
    PostAuthLogoutRequestSchema,
    PostAuthLogoutDataSchema,
    PostAuthLogoutResponseSchema,
    PostAuthRedeemMembershipRequestSchema,
    PostAuthRedeemMembershipDataSchema,
    PostAuthRedeemMembershipResponseSchema,
    PostAuthRegisterRequestSchema,
    PostAuthRegisterDataSchema,
    PostAuthRegisterResponseSchema,
    PostAuthSendQqBindingCodeRequestSchema,
    PostAuthSendQqBindingCodeDataSchema,
    PostAuthSendQqBindingCodeResponseSchema,
    PostAuthUnbindQqBindingRequestSchema,
    PostAuthUnbindQqBindingDataSchema,
    PostAuthUnbindQqBindingResponseSchema,
    PostAuthVerifyQqBindingRequestSchema,
    PostAuthVerifyQqBindingDataSchema,
    PostAuthVerifyQqBindingResponseSchema,
    PutAuthEventSubscriptionsRequestSchema,
    PutAuthEventSubscriptionsDataSchema,
    PutAuthEventSubscriptionsResponseSchema,
    PutAuthFavoritesRequestSchema,
    PutAuthFavoritesDataSchema,
    PutAuthFavoritesResponseSchema,
    PutAuthSubscriptionsRequestSchema,
    PutAuthSubscriptionsDataSchema,
    PutAuthSubscriptionsResponseSchema
} from '~/server/generated/proto/opencrh/v2/auth_pb';
import {
    deleteAuthApiKeyV2Adapter,
    deleteAuthAuthorizationV2Adapter,
    deleteAuthEventSubscriptionsV2Adapter,
    deleteAuthFavoritesV2Adapter,
    deleteAuthSubscriptionV2Adapter,
    getAuthApiKeysV2Adapter,
    getAuthAuthorizationsV2Adapter,
    getAuthEventSubscriptionsV2Adapter,
    getAuthFavoritesV2Adapter,
    getAuthMeV2Adapter,
    getAuthMembershipsV2Adapter,
    getAuthSettingsV2Adapter,
    getAuthSubscriptionsV2Adapter,
    patchAuthPasswordV2Adapter,
    patchAuthSettingsV2Adapter,
    patchAuthSubscriptionV2Adapter,
    postAuthApiKeysV2Adapter,
    postAuthLoginV2Adapter,
    postAuthLogoutV2Adapter,
    postAuthRedeemMembershipV2Adapter,
    postAuthRegisterV2Adapter,
    postAuthSendQqBindingCodeV2Adapter,
    postAuthUnbindQqBindingV2Adapter,
    postAuthVerifyQqBindingV2Adapter,
    putAuthEventSubscriptionsV2Adapter,
    putAuthFavoritesV2Adapter,
    putAuthSubscriptionsV2Adapter
} from '~/server/utils/api/v2/adapters/auth';
import { API_SCOPES } from '~/server/utils/api/scopes/apiScopes';

function favoriteEmuIds(data: unknown): number[] {
    return (
        (data as { items?: Array<{ target?: { emuId?: number } }> }).items
            ?.map((item) => item.target?.emuId)
            .filter((id): id is number => id !== undefined) ?? []
    );
}

function eventSubscriptionEmuIds(data: unknown): number[] {
    return (
        (data as { items?: Array<{ target?: { emuId?: number } }> }).items
            ?.map((item) => item.target?.emuId)
            .filter((id): id is number => id !== undefined) ?? []
    );
}

export const AUTH_MANIFEST_ENTRIES = {
    GetAuthMe: defineV2Operation({
        operationName: 'GetAuthMe',
        method: 'GET',
        pathTemplate: '/api/v2/auth/me',
        requestSchema: GetAuthMeRequestSchema,
        dataSchema: GetAuthMeDataSchema,
        responseSchema: GetAuthMeResponseSchema,
        requiredScopes: [API_SCOPES.auth.me],
        cors: true,
        cost: { kind: 'fixed', key: 'authMe' },
        bodyMode: 'none',
        handler: getAuthMeV2Adapter
    }),
    GetAuthApiKeys: defineV2Operation({
        operationName: 'GetAuthApiKeys',
        method: 'GET',
        pathTemplate: '/api/v2/auth/api-keys',
        requestSchema: GetAuthApiKeysRequestSchema,
        dataSchema: GetAuthApiKeysDataSchema,
        responseSchema: GetAuthApiKeysResponseSchema,
        requiredScopes: [API_SCOPES.auth.apiKeys.read],
        cors: false,
        cost: { kind: 'fixed', key: 'authListApiKeys' },
        bodyMode: 'none',
        handler: getAuthApiKeysV2Adapter
    }),
    PostAuthApiKeys: defineV2Operation({
        operationName: 'PostAuthApiKeys',
        method: 'POST',
        pathTemplate: '/api/v2/auth/api-keys',
        requestSchema: PostAuthApiKeysRequestSchema,
        dataSchema: PostAuthApiKeysDataSchema,
        responseSchema: PostAuthApiKeysResponseSchema,
        requiredScopes: [API_SCOPES.auth.apiKeys.create],
        cors: false,
        cost: { kind: 'fixed', key: 'authIssueApiKey' },
        bodyMode: 'optional',
        handler: postAuthApiKeysV2Adapter
    }),
    DeleteAuthApiKey: defineV2Operation({
        operationName: 'DeleteAuthApiKey',
        method: 'DELETE',
        pathTemplate: '/api/v2/auth/api-keys/:revokeId',
        requestSchema: DeleteAuthApiKeyRequestSchema,
        dataSchema: DeleteAuthApiKeyDataSchema,
        responseSchema: DeleteAuthApiKeyResponseSchema,
        requiredScopes: [API_SCOPES.auth.apiKeys.revoke],
        cors: false,
        cost: { kind: 'fixed', key: 'authRevokeApiKey' },
        bodyMode: 'none',
        handler: deleteAuthApiKeyV2Adapter
    }),
    GetAuthAuthorizations: defineV2Operation({
        operationName: 'GetAuthAuthorizations',
        method: 'GET',
        pathTemplate: '/api/v2/auth/authorizations',
        requestSchema: GetAuthAuthorizationsRequestSchema,
        dataSchema: GetAuthAuthorizationsDataSchema,
        responseSchema: GetAuthAuthorizationsResponseSchema,
        requiredScopes: [API_SCOPES.auth.authorizations.read],
        cors: false,
        cost: { kind: 'fixed', key: 'authListAuthorizations' },
        bodyMode: 'none',
        handler: getAuthAuthorizationsV2Adapter
    }),
    DeleteAuthAuthorization: defineV2Operation({
        operationName: 'DeleteAuthAuthorization',
        method: 'DELETE',
        pathTemplate: '/api/v2/auth/authorizations/:clientId',
        requestSchema: DeleteAuthAuthorizationRequestSchema,
        dataSchema: DeleteAuthAuthorizationDataSchema,
        responseSchema: DeleteAuthAuthorizationResponseSchema,
        requiredScopes: [API_SCOPES.auth.authorizations.revoke],
        cors: false,
        cost: { kind: 'fixed', key: 'authRevokeAuthorization' },
        bodyMode: 'none',
        handler: deleteAuthAuthorizationV2Adapter
    }),
    GetAuthEventSubscriptions: defineV2Operation({
        operationName: 'GetAuthEventSubscriptions',
        method: 'GET',
        pathTemplate: '/api/v2/auth/event-subscriptions',
        requestSchema: GetAuthEventSubscriptionsRequestSchema,
        dataSchema: GetAuthEventSubscriptionsDataSchema,
        responseSchema: GetAuthEventSubscriptionsResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.read],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        mappings: {
            emuCode: eventSubscriptionEmuIds
        },
        handler: getAuthEventSubscriptionsV2Adapter
    }),
    PutAuthEventSubscriptions: defineV2Operation({
        operationName: 'PutAuthEventSubscriptions',
        method: 'PUT',
        pathTemplate: '/api/v2/auth/event-subscriptions',
        requestSchema: PutAuthEventSubscriptionsRequestSchema,
        dataSchema: PutAuthEventSubscriptionsDataSchema,
        responseSchema: PutAuthEventSubscriptionsResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.write],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        mappings: {
            emuCode: eventSubscriptionEmuIds
        },
        handler: putAuthEventSubscriptionsV2Adapter
    }),
    DeleteAuthEventSubscriptions: defineV2Operation({
        operationName: 'DeleteAuthEventSubscriptions',
        method: 'DELETE',
        pathTemplate: '/api/v2/auth/event-subscriptions',
        requestSchema: DeleteAuthEventSubscriptionsRequestSchema,
        dataSchema: DeleteAuthEventSubscriptionsDataSchema,
        responseSchema: DeleteAuthEventSubscriptionsResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.write],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        mappings: {
            emuCode: eventSubscriptionEmuIds
        },
        handler: deleteAuthEventSubscriptionsV2Adapter
    }),
    GetAuthFavorites: defineV2Operation({
        operationName: 'GetAuthFavorites',
        method: 'GET',
        pathTemplate: '/api/v2/auth/favorites',
        requestSchema: GetAuthFavoritesRequestSchema,
        dataSchema: GetAuthFavoritesDataSchema,
        responseSchema: GetAuthFavoritesResponseSchema,
        requiredScopes: [API_SCOPES.auth.favorites.read],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        mappings: {
            emuCode: favoriteEmuIds
        },
        handler: getAuthFavoritesV2Adapter
    }),
    PutAuthFavorites: defineV2Operation({
        operationName: 'PutAuthFavorites',
        method: 'PUT',
        pathTemplate: '/api/v2/auth/favorites',
        requestSchema: PutAuthFavoritesRequestSchema,
        dataSchema: PutAuthFavoritesDataSchema,
        responseSchema: PutAuthFavoritesResponseSchema,
        requiredScopes: [API_SCOPES.auth.favorites.write],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        mappings: {
            emuCode: favoriteEmuIds
        },
        handler: putAuthFavoritesV2Adapter
    }),
    DeleteAuthFavorites: defineV2Operation({
        operationName: 'DeleteAuthFavorites',
        method: 'DELETE',
        pathTemplate: '/api/v2/auth/favorites',
        requestSchema: DeleteAuthFavoritesRequestSchema,
        dataSchema: DeleteAuthFavoritesDataSchema,
        responseSchema: DeleteAuthFavoritesResponseSchema,
        requiredScopes: [API_SCOPES.auth.favorites.write],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        mappings: {
            emuCode: favoriteEmuIds
        },
        handler: deleteAuthFavoritesV2Adapter
    }),
    PostAuthLogin: defineV2Operation({
        operationName: 'PostAuthLogin',
        method: 'POST',
        pathTemplate: '/api/v2/auth/login',
        requestSchema: PostAuthLoginRequestSchema,
        dataSchema: PostAuthLoginDataSchema,
        responseSchema: PostAuthLoginResponseSchema,
        requiredScopes: [],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'required',
        quotaBypassAnonymous: true,
        authRateLimitKey: 'login',
        handler: postAuthLoginV2Adapter
    }),
    PostAuthRegister: defineV2Operation({
        operationName: 'PostAuthRegister',
        method: 'POST',
        pathTemplate: '/api/v2/auth/register',
        requestSchema: PostAuthRegisterRequestSchema,
        dataSchema: PostAuthRegisterDataSchema,
        responseSchema: PostAuthRegisterResponseSchema,
        requiredScopes: [],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'required',
        quotaBypassAnonymous: true,
        authRateLimitKey: 'register',
        handler: postAuthRegisterV2Adapter
    }),
    PostAuthLogout: defineV2Operation({
        operationName: 'PostAuthLogout',
        method: 'POST',
        pathTemplate: '/api/v2/auth/logout',
        requestSchema: PostAuthLogoutRequestSchema,
        dataSchema: PostAuthLogoutDataSchema,
        responseSchema: PostAuthLogoutResponseSchema,
        requiredScopes: [API_SCOPES.auth.logout],
        cors: false,
        cost: { kind: 'fixed', key: 'authLogout' },
        bodyMode: 'none',
        handler: postAuthLogoutV2Adapter
    }),
    GetAuthMemberships: defineV2Operation({
        operationName: 'GetAuthMemberships',
        method: 'GET',
        pathTemplate: '/api/v2/auth/memberships',
        requestSchema: GetAuthMembershipsRequestSchema,
        dataSchema: GetAuthMembershipsDataSchema,
        responseSchema: GetAuthMembershipsResponseSchema,
        requiredScopes: [API_SCOPES.auth.me],
        cors: true,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: getAuthMembershipsV2Adapter
    }),
    PostAuthRedeemMembership: defineV2Operation({
        operationName: 'PostAuthRedeemMembership',
        method: 'POST',
        pathTemplate: '/api/v2/auth/memberships/redeem',
        requestSchema: PostAuthRedeemMembershipRequestSchema,
        dataSchema: PostAuthRedeemMembershipDataSchema,
        responseSchema: PostAuthRedeemMembershipResponseSchema,
        requiredScopes: [API_SCOPES.auth.memberships.redeem],
        cors: true,
        cost: { kind: 'fixed', key: 'authRedeemMembership' },
        bodyMode: 'optional',
        handler: postAuthRedeemMembershipV2Adapter
    }),
    PatchAuthPassword: defineV2Operation({
        operationName: 'PatchAuthPassword',
        method: 'PATCH',
        pathTemplate: '/api/v2/auth/password',
        requestSchema: PatchAuthPasswordRequestSchema,
        dataSchema: PatchAuthPasswordDataSchema,
        responseSchema: PatchAuthPasswordResponseSchema,
        requiredScopes: [API_SCOPES.auth.password.update],
        cors: false,
        cost: { kind: 'fixed', key: 'authChangePassword' },
        bodyMode: 'required',
        handler: patchAuthPasswordV2Adapter
    }),
    PostAuthSendQqBindingCode: defineV2Operation({
        operationName: 'PostAuthSendQqBindingCode',
        method: 'POST',
        pathTemplate: '/api/v2/auth/qq-binding/send-code',
        requestSchema: PostAuthSendQqBindingCodeRequestSchema,
        dataSchema: PostAuthSendQqBindingCodeDataSchema,
        responseSchema: PostAuthSendQqBindingCodeResponseSchema,
        requiredScopes: [API_SCOPES.auth.qqBinding.send],
        cors: false,
        cost: { kind: 'fixed', key: 'authSendQqBindingCode' },
        bodyMode: 'required',
        handler: postAuthSendQqBindingCodeV2Adapter
    }),
    PostAuthUnbindQqBinding: defineV2Operation({
        operationName: 'PostAuthUnbindQqBinding',
        method: 'POST',
        pathTemplate: '/api/v2/auth/qq-binding/unbind',
        requestSchema: PostAuthUnbindQqBindingRequestSchema,
        dataSchema: PostAuthUnbindQqBindingDataSchema,
        responseSchema: PostAuthUnbindQqBindingResponseSchema,
        requiredScopes: [API_SCOPES.auth.qqBinding.unbind],
        cors: false,
        cost: { kind: 'fixed', key: 'authUnbindQqBinding' },
        bodyMode: 'none',
        handler: postAuthUnbindQqBindingV2Adapter
    }),
    PostAuthVerifyQqBinding: defineV2Operation({
        operationName: 'PostAuthVerifyQqBinding',
        method: 'POST',
        pathTemplate: '/api/v2/auth/qq-binding/verify',
        requestSchema: PostAuthVerifyQqBindingRequestSchema,
        dataSchema: PostAuthVerifyQqBindingDataSchema,
        responseSchema: PostAuthVerifyQqBindingResponseSchema,
        requiredScopes: [API_SCOPES.auth.qqBinding.verify],
        cors: false,
        cost: { kind: 'fixed', key: 'authVerifyQqBinding' },
        bodyMode: 'required',
        handler: postAuthVerifyQqBindingV2Adapter
    }),
    GetAuthSettings: defineV2Operation({
        operationName: 'GetAuthSettings',
        method: 'GET',
        pathTemplate: '/api/v2/auth/settings',
        requestSchema: GetAuthSettingsRequestSchema,
        dataSchema: GetAuthSettingsDataSchema,
        responseSchema: GetAuthSettingsResponseSchema,
        requiredScopes: [API_SCOPES.auth.settings.read],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'none',
        handler: getAuthSettingsV2Adapter
    }),
    PatchAuthSettings: defineV2Operation({
        operationName: 'PatchAuthSettings',
        method: 'PATCH',
        pathTemplate: '/api/v2/auth/settings',
        requestSchema: PatchAuthSettingsRequestSchema,
        dataSchema: PatchAuthSettingsDataSchema,
        responseSchema: PatchAuthSettingsResponseSchema,
        requiredScopes: [API_SCOPES.auth.settings.write],
        cors: false,
        cost: { kind: 'none' },
        bodyMode: 'optional',
        handler: patchAuthSettingsV2Adapter
    }),
    GetAuthSubscriptions: defineV2Operation({
        operationName: 'GetAuthSubscriptions',
        method: 'GET',
        pathTemplate: '/api/v2/auth/subscriptions',
        requestSchema: GetAuthSubscriptionsRequestSchema,
        dataSchema: GetAuthSubscriptionsDataSchema,
        responseSchema: GetAuthSubscriptionsResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.read],
        cors: false,
        cost: { kind: 'fixed', key: 'authListSubscriptions' },
        bodyMode: 'none',
        handler: getAuthSubscriptionsV2Adapter
    }),
    PutAuthSubscriptions: defineV2Operation({
        operationName: 'PutAuthSubscriptions',
        method: 'PUT',
        pathTemplate: '/api/v2/auth/subscriptions',
        requestSchema: PutAuthSubscriptionsRequestSchema,
        dataSchema: PutAuthSubscriptionsDataSchema,
        responseSchema: PutAuthSubscriptionsResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.write],
        cors: false,
        cost: { kind: 'fixed', key: 'authUpsertSubscription' },
        bodyMode: 'optional',
        handler: putAuthSubscriptionsV2Adapter
    }),
    DeleteAuthSubscription: defineV2Operation({
        operationName: 'DeleteAuthSubscription',
        method: 'DELETE',
        pathTemplate: '/api/v2/auth/subscriptions/:id',
        requestSchema: DeleteAuthSubscriptionRequestSchema,
        dataSchema: DeleteAuthSubscriptionDataSchema,
        responseSchema: DeleteAuthSubscriptionResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.write],
        cors: false,
        cost: { kind: 'fixed', key: 'authDeleteSubscription' },
        bodyMode: 'none',
        handler: deleteAuthSubscriptionV2Adapter
    }),
    PatchAuthSubscription: defineV2Operation({
        operationName: 'PatchAuthSubscription',
        method: 'PATCH',
        pathTemplate: '/api/v2/auth/subscriptions/:id',
        requestSchema: PatchAuthSubscriptionRequestSchema,
        dataSchema: PatchAuthSubscriptionDataSchema,
        responseSchema: PatchAuthSubscriptionResponseSchema,
        requiredScopes: [API_SCOPES.auth.subscriptions.write],
        cors: false,
        cost: { kind: 'fixed', key: 'authUpdateSubscription' },
        bodyMode: 'required',
        handler: patchAuthSubscriptionV2Adapter
    })
} as const;
